import Head from 'next/head'
import AppDownload from '../../components/Dashboard/AppDownload'
import BarGraphChart from '../../components/Dashboard/BarGraphChart'
import CallenderComponent from '../../components/Dashboard/CallenderComponent'
import NewsCards from '../../components/Dashboard/NewsCards'
import RecentPlayers from '../../components/Dashboard/RecentPlayers'
import TotalMembers from '../../components/Dashboard/TotalMembers'
import TrafficSource from '../../components/Dashboard/TrafficSource'
import StatsCardIcon from '../../components/SVGs/DashboardIcons/StatsCardIcon'


export default function Home ()
{

    const smallCardsData = [
        {
            title: 'Total training',
            count: '12,540',
            percentage: '+ 16.24 %'
        },
        {
            title: 'Total matches',
            count: '3,540',
            percentage: '+ 16.24 %'
        },
        {
            title: 'Total tournament',
            count: '810',
            percentage: '+ 16.24 %'
        },
        {
            title: 'Total events',
            count: '810',
            percentage: '+ 16.24 %'
        }
    ]

    return (
        <div className='  bg-[#FAFAFC] flex-1 self-stretch px-[20px] py-[20px] lg:py-[20px] xl:py-[36px] lg:pl-[20px] lg:pr-[30px]' >
            <Head>
                <title>Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                {/* Statistics cards start */ }
                <div className='grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-[15px] sm:gap-[26px] '>
                    { smallCardsData.map((item, index) =>
                    {
                        return (
                            <StatisticsCard
                                key={ index + '' }
                                data={ item }
                            />
                        )
                    }) }
                </div>
                {/* Statistics cards end */ }
                <div className='flex flex-col lg:flex-row lg:space-x-[30px] '>
                    <div className='lg:flex-[68] relative'>

                        {/* Bar graph */ }
                        <BarGraphChart />
                        <div className='flex flex-col sm:flex-row mt-[33px] sm:space-x-[33px] space-y-[26px] sm:space-y-0'>
                            <AppDownload />
                            <TotalMembers />
                        </div>
                    </div>
                    <div className='self-stretch lg:flex-[32] relative mt-[30px] flex flex-col sm:flex-row space-x-0 lg:space-x-0 
                    sm:space-x-[33px] lg:flex-col  space-y-[30px] sm:space-y-0   lg:justify-between '>
                        <RecentPlayers />
                        <TrafficSource />
                    </div>
                    {/* <div className='self-stretch lg:flex-[32] relative mt-5 lg:mt-0 '> */ }
                    {/* <CallenderComponent /> */ }
                    {/* <NewsCards /> */ }
                    {/* </div> */ }
                </div>
            </div>
        </div>
    )
}


const StatisticsCard = ({ data }) =>
{
    return (
        <div className=' bg-white py-[17px] pl-[17px] pr-[11px]  rounded-[8px] flex flex-col space-y-[13px]  '>
            <div >
                <h1 className='text-dark-gray font-normal text-sm'>{ data.title }</h1>
            </div>
            <div className=' flex flex-col xl:flex-row justify-between'>
                <h1 className='font-bold text-[#1E1E1E] text-2xl'>{ data.count }</h1>
                <div className=' flex items-center space-x-1'>
                    <StatsCardIcon />
                    <h1 className='text-myellow text-xs '>{ data.percentage }</h1>
                </div>
            </div>
        </div>
    )
}